    local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
    local Window = Library.CreateLib("ROBLOX Hub", "Serpent")
    local Tab = Window:NewTab("Main")
    local Section = Tab:NewSection("Basically nothing")
    local Tab = Window:NewTab("ROBLOX Scripts")
    local Section = Tab:NewSection("King Piece")
Section:NewButton("Click to Execute", "King Piece", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end)
    local Section = Tab:NewSection("My Hero Mania")
Section:NewButton("Click to Execute", "My Hero Mania", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end)
    local Section = Tab:NewSection("Psycho 100: Infinity")
Section:NewButton("Click to Execute", "Psycho 100: Infinity", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end)
    local Section = Tab:NewSection("Project XL")
Section:NewButton("Click to Execute", "Project XL", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end)
    local Section = Tab:NewSection("DBOG")
Section:NewButton("Click to Execute", "DBOG", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end)
    local Section = Tab:NewSection("Anime Battle Simulator")
Section:NewButton("Click to Execute", "Anime Battle Simulator", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end)
    local Section = Tab:NewSection("Ro-Slayers")
Section:NewButton("Click to Execute", "Ro-Slayers", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end)
    local Section = Tab:NewSection("Fairy Tale Lost Soul")
Section:NewButton("Click to Execute", "Fairy Tale Lost Soul", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end)
    local Section = Tab:NewSection("Heroes Legacy")
Section:NewButton("Click to Execute", "Heroes Legacy", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end)
    local Section = Tab:NewSection("Pet Battle Simulator")
Section:NewButton("Click to Execute", "Pet Battle Simulator Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end)
    local Section = Tab:NewSection("Shark Evolution")
Section:NewButton("Click to Execute", "Shark Evolution Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end)
    local Section = Tab:NewSection("RPG Simulator")
Section:NewButton("Click to Execute", "RPG Simulator Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end)
    local Section = Tab:NewSection("Bomb Simulator")
Section:NewButton("Click to Execute", "Bomb Simulator Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end)
    local Section = Tab:NewSection("Gun Simulator")
Section:NewButton("Click to Execute", "Gun Simulator Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end) 
    local Section = Tab:NewSection("Project X")
Section:NewButton("Click to Execute", "Project X Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end)    
    local Section = Tab:NewSection("Ramen Simulator")
Section:NewButton("Click to Execute", "Ramen Simulator Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end)
    local Section = Tab:NewSection("Monster Attack")
Section:NewButton("Click to Execute", "Monster Attack Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end)
    local Section = Tab:NewSection("Reaper Simulator 2")
Section:NewButton("Click to Execute", "Reaper Simulator 2 Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end)    
    local Section = Tab:NewSection("Lifting Simulator")
Section:NewButton("Click to Execute", "Lifting Simulator Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end)    
    local Section = Tab:NewSection("Bulding Simulator 2")
Section:NewButton("Click to Execute", "Bulding Simulator 2 Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end)    
    local Section = Tab:NewSection("World Zero")
Section:NewButton("Click to Execute", "World Zero Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/PurpIeRaspberry/HimikoTogaScripts/main/Himiko%20Toga.lua"))()
    print("Clicked")
end)     
    local Section = Tab:NewSection("Murder Mystery 2")
Section:NewButton("Click to Execute", "Murder Mystery 2 Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Ethanoj1/EclipseMM2/master/Script", true))()
    print("Clicked")
end)        
    local Section = Tab:NewSection("Phantom Forces")
Section:NewButton("Click to Execute", "Phantom Forces Script", function()
    loadstring(game:HttpGet("https://bruh.keshsenpai.com/.lua"))()
    print("Clicked")
end)    
    local Section = Tab:NewSection("Jailbreak Script")
Section:NewButton("Click to Execute", "Jailbreak Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/alohabeach/Main/master/Scripts/JailbreakAutoRob.lua"))()
    print("Clicked")
end)
    local Section = Tab:NewSection("Ro-Ghoul Script")
Section:NewButton("Click to Execute", "Ro-Ghoul Script", function()
    loadstring(game:HttpGetAsync(("https://raw.githubusercontent.com/z4gs/scripts/master/Ro-Ghoul%20Auto%20Farm.lua")))()
    print("Clicked")
end)
    local Tab = Window:NewTab("FE Player")
    local Section = Tab:NewSection("WalkSpeed")
    Section:NewSlider("WalkSpeed", "Increases and Decreases Speed", 500, 16, function(s) -- 500 (MaxValue) | 0 (MinValue)
    game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = s
end)
    local Section = Tab:NewSection("JumpPower")
    Section:NewSlider("JumpPower", "To increase or decrease your jump-power", 500, 4, function(s) -- 500 (MaxValue) | 0 (MinValue)
    game.Players.LocalPlayer.Character.Humanoid.JumpPower = s
end)
    local Section = Tab:NewSection("Floating Hat")
Section:NewButton("Click to Execute", "Floating Hat", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/PurpIeRaspberry/FloatyHat/main/FloatyHat.lua'))()
    print("Clicked")
end)    
    local Section = Tab:NewSection("Infinite Jump")
    Section:NewButton("Click to Execute", "Infinite Jump", function()
    InfiniteJumpEnabled = true
game:GetService("UserInputService").JumpRequest:connect(function()
	if InfiniteJumpEnabled then
		game:GetService"Players".LocalPlayer.Character:FindFirstChildOfClass'Humanoid':ChangeState("Jumping")
	end

end)
end)
